// Package tracetest provides utilities and helpers for unit testing your package
// that requires the need of tracking and validating the generated spans by your
// package.
//
// The tracetest package simplifies the following features:
//   - Mock trace spans without requiring a remote backend server to export the spans.
//   - Captures the spans generated by the recorder.
//
// Furthermore, this package implements tengcorux's tracer package. Hence, to do
// checks one must assert the type to tracetest struct to be able to retrieve
// the spans.
//
// Example usages:
//
//	func TestMyFunction(t *testing.T) {
//		tracer := tracetest.NewTracer()
//		ctx, span := tracer.StartSpan(context.Background(), "some_name")
//		defer span.End()
//
//		recorder := tracer.Recorder()
//		spans := recorder.StartedSpans() // or recorder.EndedSpans()
//		_ = spans // do something with it.
//	}
package tracetest
